[0m12:05:31.080088 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1084dc380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108eacd10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108eacad0>]}


============================== 12:05:31.083050 | 884b66b5-b8ea-4d7a-984b-329378e4c5ba ==============================
[0m12:05:31.083050 [info ] [MainThread]: Running with dbt=1.10.4
[0m12:05:31.083383 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/etiennelancelle/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt init dbt-dataplatform', 'send_anonymous_usage_stats': 'True'}
[0m12:05:38.700038 [debug] [MainThread]: Starter project path: /Users/etiennelancelle/Documents/Projets/Dev/ELA_DP/.venv/lib/python3.12/site-packages/dbt/include/starter_project
[0m12:05:38.714195 [info ] [MainThread]: 
Your new dbt project "dbt_dataplatform" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:05:38.714906 [info ] [MainThread]: Setting up your profile.
[0m12:06:16.222253 [info ] [MainThread]: Profile dbt_dataplatform written to /Users/etiennelancelle/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:06:16.230894 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 45.19557, "process_in_blocks": "0", "process_kernel_time": 0.454989, "process_mem_max_rss": "347553792", "process_out_blocks": "0", "process_user_time": 1.675163}
[0m12:06:16.234260 [debug] [MainThread]: Command `dbt init` succeeded at 12:06:16.233885 after 45.20 seconds
[0m12:06:16.235722 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108784fb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11c922ea0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11dceaed0>]}
[0m12:06:16.236543 [debug] [MainThread]: Flushing usage events
[0m12:06:16.630842 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:15:17.932060 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d66150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1073e9310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1073e9070>]}


============================== 12:15:17.935226 | d0110ec9-d776-40af-8176-38d5d46688fb ==============================
[0m12:15:17.935226 [info ] [MainThread]: Running with dbt=1.10.4
[0m12:15:17.935559 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/etiennelancelle/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'invocation_command': 'dbt run --select lake_spotify__stg_tracks_raw', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:15:17.935895 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/etiennelancelle/Documents/Projets/Dev/ELA_DP/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:15:17.936895 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.046642542, "process_in_blocks": "0", "process_kernel_time": 0.145021, "process_mem_max_rss": "105152512", "process_out_blocks": "0", "process_user_time": 0.682896}
[0m12:15:17.937165 [debug] [MainThread]: Command `dbt run` failed at 12:15:17.937117 after 0.05 seconds
[0m12:15:17.937353 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1072c0770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102cf7980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107362210>]}
[0m12:15:17.937527 [debug] [MainThread]: Flushing usage events
[0m12:15:18.382782 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:15:57.988268 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1049bf9e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1073fd160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1073fcef0>]}


============================== 12:15:57.991361 | ea33c0ae-7584-4eae-947f-62ffa1b414a6 ==============================
[0m12:15:57.991361 [info ] [MainThread]: Running with dbt=1.10.4
[0m12:15:57.991707 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/etiennelancelle/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run --select lake_spotify__stg_tracks_raw', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:15:57.992028 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/etiennelancelle/Documents/Projets/Dev/ELA_DP/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:15:57.992969 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.04690296, "process_in_blocks": "0", "process_kernel_time": 0.143798, "process_mem_max_rss": "104988672", "process_out_blocks": "0", "process_user_time": 0.686536}
[0m12:15:57.993244 [debug] [MainThread]: Command `dbt run` failed at 12:15:57.993198 after 0.05 seconds
[0m12:15:57.993445 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1049bf9e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1073feb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1073fea80>]}
[0m12:15:57.993617 [debug] [MainThread]: Flushing usage events
[0m12:15:58.380163 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m02:15:34.389795 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1030f86e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105718fe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105718d40>]}


============================== 02:15:34.393776 | 67214061-19b6-4d00-9671-2a5d3e3fc1d3 ==============================
[0m02:15:34.393776 [info ] [MainThread]: Running with dbt=1.10.4
[0m02:15:34.394212 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/etiennelancelle/Documents/Projets/Dev/ELA_DP/src/dbt_dataplatform', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --target prd', 'send_anonymous_usage_stats': 'True'}
[0m02:15:34.394605 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/etiennelancelle/Documents/Projets/Dev/ELA_DP/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m02:15:34.396269 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.06288433, "process_in_blocks": "0", "process_kernel_time": 0.162771, "process_mem_max_rss": "104529920", "process_out_blocks": "0", "process_user_time": 0.74757}
[0m02:15:34.396635 [debug] [MainThread]: Command `dbt run` failed at 02:15:34.396572 after 0.06 seconds
[0m02:15:34.396893 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1056dfb90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104dc9220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105718f20>]}
[0m02:15:34.397125 [debug] [MainThread]: Flushing usage events
[0m02:15:34.793574 [debug] [MainThread]: An error was encountered while trying to flush usage events
